name: Bug Report
description: File a bug report
body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this bug report!
- type: textarea
  id: what-happened
  attributes:
    label: What happened?
    description: Also, what did you expect to happen? You can upload any screenshots here to help explain the problem (but please do not upload images of the mascot).
    placeholder: Say what happened!
  validations:
    required: true
- type: input
  id: url
  attributes:
    label: URL
    description: If possible, could you provide an example URL of where the problem is happening? (However, please do not post NSFW URLs.)
    placeholder: "Example: https://www.example.com/right-here"
- type: input
  id: version
  attributes:
    label: Version
    description: What version are you using?
    placeholder: "Example: 0.7"
- type: input
  id: browser
  attributes:
    label: Browser
    description: What browser and browser version are you using?
    placeholder: "Example: Chrome 100"
- type: input
  id: os
  attributes:
    label: OS
    description: What operating system are you using?
    placeholder: "Example: Windows"
- type: dropdown
  id: platform
  attributes:
    label: Platform
    description: What platform are you on? (Desktop means PC or Laptop while Mobile means Phone or Tablet.)
    options:
      - Desktop
      - Mobile
