name: Bug Report
description: File a bug report
body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this bug report!
- type: textarea
  id: what-happened
  attributes:
    label: What happened?
    description: Also tell us, what did you expect to happen?
    placeholder: Tell us what you see!
  validations:
    required: true
- type: input
  id: url
  attributes:
    label: URL
    description: If possible, please provide an example URL of where the problem is happening.
    placeholder: "Example: https://www.example.com/right-here"
- type: input
  id: version
  attributes:
    label: Version
    description: What version of the extension are you using?
    placeholder: "Example: 0.7"
- type: input
  id: browser
  attributes:
    label: Browser Version
    description: What browser and browser version are you using?
    placeholder: "Example: Chrome 110"
- type: input
  id: os
  attributes:
    label: OS
    description: What operating system are you using?
    placeholder: "Example: Windows"
- type: dropdown
  id: platform
  attributes:
    label: What platform are you on?
    options:
      - Desktop
      - Mobile
